### ISSUE TITLE
Hi, Could you please update the requirement

### ISSUE THREAD

**Issue by Josh-Fan** [iikka-v/ML-NDT#1]
Hello there,
I found I cannot run the code in python 3.7.4, 
always with the error

Using TensorFlow backend.
Traceback (most recent call last):
  File "c:/Users/Josh-/Documents/CSM_lecture/Individual_Project/ML_NDT_application/Test_DL_application/ML-NDT-master/src/train.py", line 10, in <module>
    import keras
  File "C:\Users\Josh-\Documents\CSM_lecture\Individual_Project\ML_NDT_application\Test_DL_application\ML-NDT-master\python-venv\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Josh-\Documents\CSM_lecture\Individual_Project\ML_NDT_application\Test_DL_application\ML-NDT-master\python-venv\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Josh-\Documents\CSM_lecture\Individual_Project\ML_NDT_application\Test_DL_application\ML-NDT-master\python-venv\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Josh-\Documents\CSM_lecture\Individual_Project\ML_NDT_application\Test_DL_application\ML-NDT-master\python-venv\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Josh-\Documents\CSM_lecture\Individual_Project\ML_NDT_application\Test_DL_application\ML-NDT-master\python-venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

I think it is a version issue in keras, tensorflow or python, 
my python version 3.7.4
keras version 2.2.4
tensorflow version 1.14.0

Please help, this error code happen every time, no matter which version of keras or tensorflow I have installed.

Thank you!

**Comment by Josh-Fan** [comment]
I have also tried python 2.7 but end with same error.

**Comment by iikka-v** [comment]
Tested using:
    Python: 2.7.15
    Keras: 2.1.6
    Tensorflow:1.12.0
and
    Python: 3.7.3
    Keras:2.2.4
    Tensorflow:1.14.0
under Ubuntu-Linux and Mac OS X.

By the look of the stack-trace, this seems to be a generic environment issue (and not a problem specific to this project). It seems installing Keras and Tensorflow in Windows may currently have some version issues. Python 3.5 seems to be recommended for Windows, but I do not have access to a Windows box at the moment and cannot confirm this.

**Comment by Josh-Fan** [comment]
> Tested using:
> Python: 2.7.15
> Keras: 2.1.6
> Tensorflow:1.12.0
> and
> Python: 3.7.3
> Keras:2.2.4
> Tensorflow:1.14.0
> under Ubuntu-Linux and Mac OS X.
> 
> By the look of the stack-trace, this seems to be a generic environment issue (and not a problem specific to this project). It seems installing Keras and Tensorflow in Windows may currently have some version issues. Python 3.5 seems to be recommended for Windows, but I do not have access to a Windows box at the moment and cannot confirm this.

Dear iikka-v,
Thank you for replying, that helps me so much, the code working perfectly by Python 3.5 in windows.
